apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sangativamsikrishna/argoCD-practice
    targetRevision: HEAD
    path: nginx-chart       # Folder inside repo containing the Chart.yaml
    helm:
      valueFiles:
        - values.yaml       # Optional if you want custom values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-helm   # This namespace must exist or use "default"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
